#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2022/12/19 08:43:31
# Search URL: http://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.LUMIP.MIROC.MIROC-ES2L.deforest-globe.r1i1p1f2.3hr.tas.gn.v20220506|esgf-data02.diasjp.net
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.LUMIP.MIROC.MIROC-ES2L.deforest-globe.r1i1p1f2.3hr.tas.gn.v20220506|esgf-data02.diasjp.net'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185001010300-185101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185001010300-185101010000.nc' 'SHA256' '1cc4cd17766e2ae0dfde27c3a9c62e9a6ce043e3d0d7b350b78896f9e6cedb1a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185101010300-185201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185101010300-185201010000.nc' 'SHA256' '19fc6b475a2ae30590709d0f86c969078f86ed45878f87e25aec850c1f2c639f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185201010300-185301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185201010300-185301010000.nc' 'SHA256' '614c1784e53547292bc250f21ad41dc1b91b360f0211cf2b09fb26c7a3b808a0'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185301010300-185401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185301010300-185401010000.nc' 'SHA256' '6dc3ef0e54ce22e6013a72631888fb73b4bd710c52938ad7b5913e7dc976783b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185401010300-185501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185401010300-185501010000.nc' 'SHA256' 'b87a2d4b5635f7d393065c5a036f50752a8ebe34b10e047b8cfdd1be2a37f1c5'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185501010300-185601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185501010300-185601010000.nc' 'SHA256' 'b03f724638a29ca1d2ac9fa52969d11fccd93627ad6d77f491d3bfcff3fa714e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185601010300-185701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185601010300-185701010000.nc' 'SHA256' '559b441230f884aa4b512b91766cfb0a61434393135a6eb2ce374678e98db73d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185701010300-185801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185701010300-185801010000.nc' 'SHA256' '98b943f098123962c66f554446cead6b32ba23dacb707fd007a72a309bf96023'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185801010300-185901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185801010300-185901010000.nc' 'SHA256' '11733503b9b4837bc2ee62046be0b3bc557073793982ed384914a6607d6f3a49'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185901010300-186001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185901010300-186001010000.nc' 'SHA256' '3a03e2da55cd5afba33b2f550e8cb4350230e087d5281d3f6ef716b96b09d791'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186001010300-186101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186001010300-186101010000.nc' 'SHA256' '39351d4f51df91c5e9ddae2892cc3ba1da7bf947457cbbb31ffd5e5d67ad5a75'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186101010300-186201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186101010300-186201010000.nc' 'SHA256' '5d366aa65ea3080ff5944b8ea5feadb26f389b17975ba542713e700cce6e0312'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186201010300-186301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186201010300-186301010000.nc' 'SHA256' '16d585a4a261e1df99b24327fde456cefead47e57dcc86a42291a187c920b574'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186301010300-186401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186301010300-186401010000.nc' 'SHA256' '5c7049269e442c8ca3f5dfa2e222234510c87fb3d0a8512517fab440f5dac996'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186401010300-186501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186401010300-186501010000.nc' 'SHA256' 'c29e1449326be7e9131a6c246107456a7bf8670098a45b28e284db218fd2a498'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186501010300-186601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186501010300-186601010000.nc' 'SHA256' 'c583f37ee973d59f4cae2f7d4861d9ebea050af5fdf38e54b83516dbe52e3cf6'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186601010300-186701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186601010300-186701010000.nc' 'SHA256' '9398d4d24a5755359fd743399ffbf0c9a859ce3ac4ce741f67006939bc15b4d6'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186701010300-186801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186701010300-186801010000.nc' 'SHA256' '0243f7ac3be037f02d7e5da0731964f39538d08b5807aba22abfdced07c52e3d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186801010300-186901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186801010300-186901010000.nc' 'SHA256' '1e7fe30d000dedc64049f54c8e46ac8af1fb0b3877fad76f31b913733b4a7c30'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186901010300-187001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186901010300-187001010000.nc' 'SHA256' 'bd061b76906c7d50c72946dc83705927c51bc02b10779b60b1fda28bb0a01944'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187001010300-187101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187001010300-187101010000.nc' 'SHA256' 'e1c52ba165f5fbd985bd00c26c17d461820bb103ad02b653c8f62ce04f242ae4'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187101010300-187201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187101010300-187201010000.nc' 'SHA256' '8b05d061fdb2014d8d2ce08d859e311d988b54d40a666fe32aacf67c97b633ce'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187201010300-187301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187201010300-187301010000.nc' 'SHA256' '3444c593d3c1e11f81f2dc086628fd6284d3f8170a05953a95bab64dcab7c5e9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187301010300-187401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187301010300-187401010000.nc' 'SHA256' 'a01f48974a4f41049a23494725d6874dbeb6ccedacdfb3a278507bdf712615c3'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187401010300-187501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187401010300-187501010000.nc' 'SHA256' '4cac9d25c6767bbc439acdb3535608a23893c0c2951b310a899e64554357e213'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187501010300-187601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187501010300-187601010000.nc' 'SHA256' '07e1bc83b36e8570c300666c5c5420a9fdd5996cfa90401fba54f1a35fcde62f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187601010300-187701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187601010300-187701010000.nc' 'SHA256' 'a02b879bee6d008e9e4ab744c8bf551ae00540f418616814015880cae9ff57ce'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187701010300-187801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187701010300-187801010000.nc' 'SHA256' '77377c502f64b4234d157ba493c373d2082f504d068b882c93406e9e53a1396c'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187801010300-187901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187801010300-187901010000.nc' 'SHA256' 'b72849e14efe12dd47033cb4b1d3231c84a952a25102d6c240ed655acd8065ee'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187901010300-188001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187901010300-188001010000.nc' 'SHA256' '5d955b7925d7df989c94e6e42aa0af3cb50315233296242a3428b804d5071d21'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188001010300-188101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188001010300-188101010000.nc' 'SHA256' '0359943dc8cbb2a0d95896db0262dc5544d858a40666f3da1af8b85f4b1d377c'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188101010300-188201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188101010300-188201010000.nc' 'SHA256' 'cdca59216af451c1310802c4e50caea6ccc75c0078cffc8d0a22c592e6ca07a2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188201010300-188301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188201010300-188301010000.nc' 'SHA256' 'b81e71816446737c6e9dc94aaf7acbf69ca8abc302e2525f0d48e766e112c1b2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188301010300-188401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188301010300-188401010000.nc' 'SHA256' '9dcd4e96e01de1f2327258bfa711c010fffbcac0995c422b11ec9d002dbb6eab'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188401010300-188501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188401010300-188501010000.nc' 'SHA256' '0d3f496846a5f9d2e58e2f9f31e7f4e2a6b3400177e8aaf5692c1c047ba1d45c'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188501010300-188601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188501010300-188601010000.nc' 'SHA256' '7eeaf3e747e98137ec821bb98362e6580b08c25187cbe889bfd46531fc285143'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188601010300-188701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188601010300-188701010000.nc' 'SHA256' '3a270c308d5cb9ef6cb21a4060a96f1049b0f6a97d0d4def4beea60abc77c614'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188701010300-188801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188701010300-188801010000.nc' 'SHA256' '840129d52955e7a551632f90be1c9bbd6bd318e3feda6a4b66eb22ce6e4eab94'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188801010300-188901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188801010300-188901010000.nc' 'SHA256' 'd87619f19f01e6667fe420d765d0b9af68c9c1123d323e51acc8faf1a27e1df2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188901010300-189001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188901010300-189001010000.nc' 'SHA256' '7c11209f36873640754920d5a6a059fd7a6f1a236b0b9caf252b150e4c20fbc2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189001010300-189101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189001010300-189101010000.nc' 'SHA256' 'acf6626f7ea50bd091c8ce2caf60974e1f380bfc84a846d5f7149b4adce70f2a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189101010300-189201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189101010300-189201010000.nc' 'SHA256' '19a84534001a0e3ac289cf59594dae3a6858d2e8dd6f7ae6729199ac04a07a94'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189201010300-189301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189201010300-189301010000.nc' 'SHA256' 'abeb5781091b5407bb55fbac5827c5eba5b636ee7f2eb4675c9ab3256b5b8383'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189301010300-189401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189301010300-189401010000.nc' 'SHA256' '2184e105025c979517dc482a06eb494f923cb1abb2668a18e4689139e1067427'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189401010300-189501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189401010300-189501010000.nc' 'SHA256' 'c6536592b10653ddb209b4ac1cefada83530b5ebc376323b333b3cc13a6390bf'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189501010300-189601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189501010300-189601010000.nc' 'SHA256' 'faab22ca40d5958ea0bfe186835e4f38a3cce366711e933e5c1d856d83096170'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189601010300-189701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189601010300-189701010000.nc' 'SHA256' 'daa80c24233839f217eb9b20f29d06799c2a062c236488120205e9d80f5fc624'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189701010300-189801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189701010300-189801010000.nc' 'SHA256' '31f27e4183a8c348de1f088ab02a3c88a4037cc6f3128275bb4954fed025984a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189801010300-189901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189801010300-189901010000.nc' 'SHA256' 'cff838acc3d2c5afd3197c6967f7819f540ac900daad50144bc5f115c29b7b64'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189901010300-190001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189901010300-190001010000.nc' 'SHA256' '7e10a3b92ddbfaf700bfb130bf7f6484ed2ff2d58a88c8463a9d5944e9ec5201'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190001010300-190101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190001010300-190101010000.nc' 'SHA256' '091e6f2f977fedd2ae9d19f022c67b1c5e3f1397fc0bb79e90c92fb12d7b4722'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190101010300-190201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190101010300-190201010000.nc' 'SHA256' 'a76456cfb9db7b63bed8e7b8337d45a031f1fedffded06efb0770e2248d3e7fe'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190201010300-190301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190201010300-190301010000.nc' 'SHA256' 'f9b748b84f9b080fa4b881bfddb25700dc8d9d06da72c1176d50ba6298a08f10'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190301010300-190401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190301010300-190401010000.nc' 'SHA256' 'f39323d6af3e636cd13bf16a31214184f2fc1301c16fab2d3cdd6d9496df8eb2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190401010300-190501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190401010300-190501010000.nc' 'SHA256' '7bbf8c54136dfaa67c68003d1e11a4d5293a48eee1cdadcd24d817b50b629697'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190501010300-190601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190501010300-190601010000.nc' 'SHA256' '5240fe5a3b91ed5797ac7757a8ffdd4295879988bbd32a99d10ec96d78ac2ca7'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190601010300-190701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190601010300-190701010000.nc' 'SHA256' 'ae7d59a6f2a0bcabdba84df2136571508a8e1e307cb09b336ee3e584707e2f3d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190701010300-190801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190701010300-190801010000.nc' 'SHA256' 'cf6635839ba4843f6e43e91d1eac49d04ba6ec913b5c4f18ab3fa1e2a0562484'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190801010300-190901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190801010300-190901010000.nc' 'SHA256' '4ff20c13f5dca43d142b851f0040d64faff6aca878bc1a6e766c09f9f9caa311'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190901010300-191001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190901010300-191001010000.nc' 'SHA256' 'b5b4332eade8aa5661dcf23e372be748918e1146b0bd099954f446cbf1dc4dac'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191001010300-191101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191001010300-191101010000.nc' 'SHA256' 'e8b56e657ce0a49200dd23496e145adbe9b31572c87e3ceec49ea19dfa598a0b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191101010300-191201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191101010300-191201010000.nc' 'SHA256' '5c81db72fdf4125136050648e254d44cb35e9a282387e77159686f08b4bf54cf'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191201010300-191301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191201010300-191301010000.nc' 'SHA256' '3475d763ce813c71a92d6bf3ec89b0a1b329dc489e84f1ddf045cc4fab336e51'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191301010300-191401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191301010300-191401010000.nc' 'SHA256' '940641e40d66273b67b64281c20a5f3873123e9d53efcf0eb002a37ebfbb07a6'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191401010300-191501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191401010300-191501010000.nc' 'SHA256' '6e936eb1cc56a9a49aec517db8b8964150b237a11d5b9a08900b789653507f06'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191501010300-191601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191501010300-191601010000.nc' 'SHA256' '96b1566fe22712515e0621a5bb77f073dd35e1b37d7740834354757592561a06'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191601010300-191701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191601010300-191701010000.nc' 'SHA256' '674311f1de2b047251e9a2fa6007e362483fe00377ce2ca8b29cb31036b59c8f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191701010300-191801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191701010300-191801010000.nc' 'SHA256' '8cd9a74d227b4a1f72dd981b29190256b6e2e7f8d6b3391f2d080eff887b16c8'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191801010300-191901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191801010300-191901010000.nc' 'SHA256' '9b54955e8dfc1d15e896458353c00b29a53bca65aae870ea79ada70f5b3cb7d7'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191901010300-192001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191901010300-192001010000.nc' 'SHA256' '19ed564ae23d47d0a2851528fe0ec8321ec2a0d47768859ba3c77a4576be3571'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192001010300-192101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192001010300-192101010000.nc' 'SHA256' '1d977aac1fc377e0bfe228c607fd582a10a06609dd7eb63c137380cfe3cccc5e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192101010300-192201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192101010300-192201010000.nc' 'SHA256' 'f7a3ad38811be205866d275ce75a7cb3d9790271a64bd6f8c861b2e117864929'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192201010300-192301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192201010300-192301010000.nc' 'SHA256' '8f4697b9808441fcc4875c9c5c75b7e6898fe2d3b044ba2d332b1e56c23f4f90'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192301010300-192401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192301010300-192401010000.nc' 'SHA256' '42b29c7d7704d5bad0f0b6708b44c98398d3d5473f77976041bd00bd8e6fdc80'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192401010300-192501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192401010300-192501010000.nc' 'SHA256' '79dbe22d1ef41c3066c935943f963b9bedc25f6449e73ecba2dace510a3c5be9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192501010300-192601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192501010300-192601010000.nc' 'SHA256' '1608700d823ca16878edabe2bbb7a7d0c5819fa53658807478fb5015049b2228'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192601010300-192701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192601010300-192701010000.nc' 'SHA256' '53c73b1dda20e420aae2b2474613f181c1e2964833052b2eb0186845d9ea8567'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192701010300-192801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192701010300-192801010000.nc' 'SHA256' 'afbd1d333a1a19a8da37cf33bc18d522460011ab721b60006879bfeb12f29dc8'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192801010300-192901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192801010300-192901010000.nc' 'SHA256' '9950032648b9306960e067f2e89df7a30e5d3a23336d84f158de0a7b43abae47'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192901010300-193001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192901010300-193001010000.nc' 'SHA256' 'fbec1e658427ccdd8f86b6a5248864ec1873e47d8776d2cd437825fed13b9e38'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193001010300-193101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193001010300-193101010000.nc' 'SHA256' 'fc34f0d3bce81ad5a250f678479d1bf8d2d1d6f4e7ae59d09cc2d42f33b2200a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193101010300-193201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193101010300-193201010000.nc' 'SHA256' 'd485664854417172709a8f761b1037d328814c9e3b9c5624cc715977278c7267'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193201010300-193301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193201010300-193301010000.nc' 'SHA256' '35653a56959e60b82f22e24e9c6cd9e073c98797c27953ac0ad81eead8ffc55e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193301010300-193401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193301010300-193401010000.nc' 'SHA256' '3bc14cbdfa5d1d20b73b4273eedfd419a41e21524e41b66a3cd73eee88b2f3c9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193401010300-193501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193401010300-193501010000.nc' 'SHA256' '7ac771413479217076ca7b3a28d1256fc5641017bf781ce89efc9a04d89a72db'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193501010300-193601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193501010300-193601010000.nc' 'SHA256' '8a1b088ba5b530964be7c686306a482a84e0cbe46197867908409ffe6612223d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193601010300-193701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193601010300-193701010000.nc' 'SHA256' '1967d28ad5becb35f7c5aadf107f838563b3e0af955b49cc5651f563cd05f970'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193701010300-193801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193701010300-193801010000.nc' 'SHA256' 'f61c5e6646948cb23c32bd1b51d6de4d8e1fa6a940f29c6a3d083af34a499194'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193801010300-193901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193801010300-193901010000.nc' 'SHA256' 'a3748c1932fb639de1472eaa2e6b02ac86c4dd103793078c909cc7ab11e3fa9b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193901010300-194001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193901010300-194001010000.nc' 'SHA256' '80820e36490dd613a0dba3bce68b1b1d93e9a2777a922abd7198c90b7dc63be9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194001010300-194101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194001010300-194101010000.nc' 'SHA256' '76fd346b15996129a7d57b180771e721c63b57c5bbe52cbd2c0306d2a464fe9e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194101010300-194201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194101010300-194201010000.nc' 'SHA256' 'ecb977a92e52228bfef048c56e53f1d35c482a5c37f9e9df5429b2ba6d8efe83'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194201010300-194301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194201010300-194301010000.nc' 'SHA256' '8e0725b8592171c30f24cf2c90a02fca67706ce01d98bea0e521c4a005113574'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194301010300-194401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194301010300-194401010000.nc' 'SHA256' '72ea2e1ad78b086d5294655b70fe58b280e3d9203adffc7d4bdf257767b02deb'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194401010300-194501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194401010300-194501010000.nc' 'SHA256' 'f31954ca7c5f7997c0a8251f9924a6057fc0ecb93124248f77143415dbdda3dc'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194501010300-194601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194501010300-194601010000.nc' 'SHA256' '8719030dc28a7ac3e05d1f6328e081f477b633ecc338f514dde2cb323ade7064'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194601010300-194701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194601010300-194701010000.nc' 'SHA256' 'bd89e1a4997a3d909b376581d0c54c766453f9eb24ed39f2f6a4286b74e699ca'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194701010300-194801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194701010300-194801010000.nc' 'SHA256' '85c67f27f3fe6a24e7d62edc82eecc8874172689e18f1cfaec5f922eda03b5c1'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194801010300-194901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194801010300-194901010000.nc' 'SHA256' '53105c97b262f5203824e41c4841fab07a381492ab4aebc3cc086e54c4f0179e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194901010300-195001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194901010300-195001010000.nc' 'SHA256' 'f0a3e8ab8f4e2213ca360533efbe339f9e314b21a3a9921cf413f2ff5bb7bc43'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195001010300-195101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195001010300-195101010000.nc' 'SHA256' '3d990b4ff4a0199021c9daf676ea5fa82af04762dd5f5443283a467e6cde8fee'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195101010300-195201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195101010300-195201010000.nc' 'SHA256' '24017b7951c703ecc9410aaf8b08cda6e1891063ef62e4f412eb7c7b36dc4ad3'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195201010300-195301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195201010300-195301010000.nc' 'SHA256' '70afc7302b476ae50c40f34c373f93be72a9b3a037c9e67530b4403ab7cd2b08'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195301010300-195401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195301010300-195401010000.nc' 'SHA256' '82ab6c99f20de3244f1cdd021e9e2024425df259f7c03deff71639dadd8d7d02'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195401010300-195501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195401010300-195501010000.nc' 'SHA256' '80a52890237c10e8688f347dc087931a06d7a7c69559176038c96556be51ed6e'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195501010300-195601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195501010300-195601010000.nc' 'SHA256' 'fdcd6cb41ebe6038e6fbeae733446d0fa79b86dd5f7d39e5f5dff197112ed11d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195601010300-195701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195601010300-195701010000.nc' 'SHA256' '2a2eafd46a9062577bdb522b277a09732314e6b89267580949f3e048ff267f65'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195701010300-195801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195701010300-195801010000.nc' 'SHA256' 'bac702813fddf050e5ed71ce1c803eb0bfab1dce8e4bfdd08dca8066da28b637'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195801010300-195901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195801010300-195901010000.nc' 'SHA256' 'bd6e9c6736633ab534991d81e73a098e900ac67b005e581aaf1ed9bbc0b089ad'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195901010300-196001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195901010300-196001010000.nc' 'SHA256' '5188585899d7afd7f27ee05d731317dc9113e84269af29fb97ecc11d75f5153f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196001010300-196101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196001010300-196101010000.nc' 'SHA256' '090a999979601d5737a028378a15c38a0f2700df99b55479ef8b2afae85f168a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196101010300-196201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196101010300-196201010000.nc' 'SHA256' 'bd6cfee2fbb41535acaad423933d4c7b240170dc39ba4a0eb23eddfcc930ffb6'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196201010300-196301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196201010300-196301010000.nc' 'SHA256' '96a80d7ca596987d7dd4050021cedf37c689208b020b3c574e68e61f589266d1'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196301010300-196401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196301010300-196401010000.nc' 'SHA256' '365d731bce26b899843951417b39aceeb39acc5cb493e4adabc868ff4c9adb19'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196401010300-196501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196401010300-196501010000.nc' 'SHA256' 'd5455aba5c075f24e215954d31e0fe9dfe38446d55bfe48c5e422c05ccf289eb'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196501010300-196601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196501010300-196601010000.nc' 'SHA256' 'ba76ca5dcb41b8284e85c3a4e3ac4ff828b80af0ff63976c6e39995e7aafd6d3'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196601010300-196701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196601010300-196701010000.nc' 'SHA256' '7a31d0be0e5f1f87a2421389aa5a04fff2a2aeb0b7c7a52a9a0a27f59bc229c9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196701010300-196801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196701010300-196801010000.nc' 'SHA256' '44b87de391f5b58bb41308ab51ffbeda315740264f29a55da5c109f9d4e29b74'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196801010300-196901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196801010300-196901010000.nc' 'SHA256' '498d04a7c447c7b23d642c6d9806daca17abe5c1bc6ba844452fe8aae461f961'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196901010300-197001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196901010300-197001010000.nc' 'SHA256' 'c802e1d53843aa9c2b4032afc7b20d76c04484d6e1f3fb6a4fef725d0f10d514'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197001010300-197101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197001010300-197101010000.nc' 'SHA256' 'fcbc7855e9be2d3383ab9359a17b7dfdb3182aa0489c0c0caaf2a7ead3e029e2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197101010300-197201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197101010300-197201010000.nc' 'SHA256' '54f9bab83a03759de625af301d323a9af198872c5e99361a01b7f1d3756e263d'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197201010300-197301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197201010300-197301010000.nc' 'SHA256' '7735ec4d6c52686658e0575197139a94b390682252745d27428302df8e0ca75f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197301010300-197401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197301010300-197401010000.nc' 'SHA256' '25a91c24c13f39babd2f08d43a54d4eed6c1b84b6ef0b265b31778d796cf3642'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197401010300-197501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197401010300-197501010000.nc' 'SHA256' '34a5aa48adced36356d7a72f8259edb481395969b204ffded4dc2a1030206d72'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197501010300-197601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197501010300-197601010000.nc' 'SHA256' '28c54f5d191b110691926042a0515e45570653b86b0f85f225faec7d7901955a'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197601010300-197701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197601010300-197701010000.nc' 'SHA256' '8c74869229fbfdb66e23f175506237956a64d2f36a746974e733a130814d5357'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197701010300-197801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197701010300-197801010000.nc' 'SHA256' '171a06a5757c6594178c9e44fb3fa635baedcc27d443db2e34da61d06abac844'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197801010300-197901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197801010300-197901010000.nc' 'SHA256' 'a02c1db92b3bc5fd256bc325364d3678bd5cc0b6d9dab5aba5e36fc1495981fe'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197901010300-198001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197901010300-198001010000.nc' 'SHA256' 'd437ad44be5e92182acd1877c6bb802dea7db13364172dc1132623cc9e1309f3'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198001010300-198101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198001010300-198101010000.nc' 'SHA256' 'e8e1b7a50c7ce947f5bfdc4738965425334cc45037e7945196b2a657ead90d64'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198101010300-198201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198101010300-198201010000.nc' 'SHA256' 'd8c32a326c16dcf6e24ccdd36e09a4c2eb95d68122b25fc51ceecddf96f63035'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198201010300-198301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198201010300-198301010000.nc' 'SHA256' 'c3146aafebab0ec225b3a18bb477280a70018780226a8a95c133c63f47df4fda'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198301010300-198401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198301010300-198401010000.nc' 'SHA256' '396c43b1ce4b0c5dd758ff5fcf846a85b7b5bf688d7ee79419d4766a49baae50'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198401010300-198501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198401010300-198501010000.nc' 'SHA256' '5f1f5cce7dc36477aba58686dec96fad8f4a03686ec0d7eb44069b78a77c940b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198501010300-198601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198501010300-198601010000.nc' 'SHA256' '1bd9d4ce424c14337abd46ed739611d570464ed17ded6e3b553da7fbe11b1d7f'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198601010300-198701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198601010300-198701010000.nc' 'SHA256' '635ed680aaf3a4a76834e4122d1b8c64280f3fabf53fe01534995183562db979'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198701010300-198801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198701010300-198801010000.nc' 'SHA256' '8fb880b5a97ff96682a1ebe86589315d27f3a3fbb5fea5c3522ff83edb7c8b9b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198801010300-198901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198801010300-198901010000.nc' 'SHA256' '5dcbe1f324f19ce0d187c1a73b4a40e0645ac9ecf3505b7734198f512e72d5c9'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198901010300-199001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198901010300-199001010000.nc' 'SHA256' '144a07ccf8af7210b6cc8e219e58e3e3a967b7d391e498adf8d0d5d60888b245'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199001010300-199101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199001010300-199101010000.nc' 'SHA256' '0ec645f923cdb3badd3fbcfe13cbc965fcd8b48fb79180f8754e5993bffe47b0'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199101010300-199201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199101010300-199201010000.nc' 'SHA256' 'e5af67e1405f2721e9f0d92be6ed9d51e6c722ecec4d4c4c1a9772ee873ad774'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199201010300-199301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199201010300-199301010000.nc' 'SHA256' '6a525d9be0c82b88581aa68803694721daef99dfe19c1e4e1ea6fb8c22747ae1'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199301010300-199401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199301010300-199401010000.nc' 'SHA256' 'f4c268eb679dbe5d849faf42b44a0d415674c334d11a312bc306e9e6da724c7b'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199401010300-199501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199401010300-199501010000.nc' 'SHA256' 'f6d22a082314844e21e526577732aa9867b351c29b913acd7cb6d0e5cc308d34'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199501010300-199601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199501010300-199601010000.nc' 'SHA256' 'de0f9044656ef4315e31e05746f26f3bd5c1a54cf281e3c67268cc30bbfc0285'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199601010300-199701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199601010300-199701010000.nc' 'SHA256' '8d13797c75d199f92fe69412fd7e3bf54476c66bc9a649ec64216fb70a6ae72c'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199701010300-199801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199701010300-199801010000.nc' 'SHA256' 'd556882d5f001ea30bd6982b04a7b2fd22d10d386df7b00e4da61d2052fb3b69'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199801010300-199901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199801010300-199901010000.nc' 'SHA256' '1a8dd70dc9476d4e38943aa72f950023e76ac705d01599b2357237c2a9ee8bc2'
'tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199901010300-200001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/tas/gn/v20220506/tas_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199901010300-200001010000.nc' 'SHA256' 'bd4542cd3cdac4984865ebe09d91e8149b7a7235ac85e40b7527b7474453b838'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 150 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
