#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.llnl.gov - 2022/12/19 08:42:54
# Search URL: http://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.LUMIP.MIROC.MIROC-ES2L.deforest-globe.r1i1p1f2.3hr.huss.gn.v20220506|esgf-data02.diasjp.net
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='http://esgf-node.llnl.gov/esg-search/wget/?distrib=false&dataset_id=CMIP6.LUMIP.MIROC.MIROC-ES2L.deforest-globe.r1i1p1f2.3hr.huss.gn.v20220506|esgf-data02.diasjp.net'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185001010300-185101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185001010300-185101010000.nc' 'SHA256' '330438569cbfbcffe1df4dc17c573aba5b84d17d88cc762c29928d2e0e4fd942'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185101010300-185201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185101010300-185201010000.nc' 'SHA256' '3506b60563da8858d2546db283e3444041843d19c3912b7435cecf0d683f4ff3'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185201010300-185301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185201010300-185301010000.nc' 'SHA256' '7c3dfb327ac324e9a6a22223e4ec6b6a5637e4c2bc195830132f12c901ef6525'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185301010300-185401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185301010300-185401010000.nc' 'SHA256' '4423011b7694bd727afe32fe10133538e44bec3909c665106e8e07a38d6832bb'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185401010300-185501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185401010300-185501010000.nc' 'SHA256' '042cb43ae58cf942ce2986ad55be17bbb305563236a065fe90a4b8f848d255c5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185501010300-185601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185501010300-185601010000.nc' 'SHA256' '3f31d9a0798838c1958b070ff5ec8068d6ddb5c2a1da6df2ac99df512fa70b25'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185601010300-185701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185601010300-185701010000.nc' 'SHA256' 'efb7ec74ffd4515d25757ae83bf0a73e29bd3c048a19959c7d670be8f3ac1a6b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185701010300-185801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185701010300-185801010000.nc' 'SHA256' '9ca0fb64317b5df178d7a90f3e68762dc74b787f4fa0c2408fdd5e9cb139a08d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185801010300-185901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185801010300-185901010000.nc' 'SHA256' 'd942cfccd3652a505dad1bf9ab28b2f5091a2d3a2c2aedcffc750ab42f5b88fb'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185901010300-186001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_185901010300-186001010000.nc' 'SHA256' 'a87b51797d625f42bc3d1c202ecbd5cd0ae2ce2f7525c0522ca82fad9255c3b5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186001010300-186101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186001010300-186101010000.nc' 'SHA256' '270410196042c106b637006e0b7ec3d023a15a2c270c3672d30935d3761bb95b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186101010300-186201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186101010300-186201010000.nc' 'SHA256' '807558a029c512e3ca8a8b3c93ac4deec92c412c2895b3e6963c95ea444ede39'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186201010300-186301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186201010300-186301010000.nc' 'SHA256' 'fc943d7d8fa30b6f450dedce7053460910e692309b0bfd05692bb991204866eb'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186301010300-186401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186301010300-186401010000.nc' 'SHA256' '76d52e3a8f3130e21a1dfe311ff2633ad9e65b9a6592c3006fce4746e0bc5b69'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186401010300-186501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186401010300-186501010000.nc' 'SHA256' '981455c5dba14096178981037aaa3d5729ffae7f0e3a8683ab4ae5dc854a7070'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186501010300-186601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186501010300-186601010000.nc' 'SHA256' '326f08508399d32b6ddec43342b89c4e0997ae91af81f5fc83066712bc02ba7b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186601010300-186701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186601010300-186701010000.nc' 'SHA256' '812a6a14774088eaa06508d306ea9858aefbeee628111317e566feb8bef87590'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186701010300-186801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186701010300-186801010000.nc' 'SHA256' '3ff5bf3489fbb2539b4d3818bd1b60cb40f2d95a8907d75ab1ee6ca1e8d3ab91'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186801010300-186901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186801010300-186901010000.nc' 'SHA256' 'eb33f6435deaf089034d7e64e0488ca020c0b4be8a82d3dd5e29b712e894e4ac'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186901010300-187001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_186901010300-187001010000.nc' 'SHA256' 'e43d2d0e0963128ba79b1f006123284a640c17d1aaa24077ed27c02c546d5797'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187001010300-187101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187001010300-187101010000.nc' 'SHA256' '6cabcd59929884d7be159d8b098795599c85134c8abd02a0db6da56d85201e72'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187101010300-187201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187101010300-187201010000.nc' 'SHA256' 'f01d74e2e7736d012b132f03f1cef72fe08afc5a6d7d58131beae5515d28c666'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187201010300-187301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187201010300-187301010000.nc' 'SHA256' '636fe0685ea0c9708fe3c85d59fadf945028676e4f58411cdf774862e3fb12a4'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187301010300-187401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187301010300-187401010000.nc' 'SHA256' 'bc248bc92cd59ed839dbf0b92bd09bf999010c46cef1d8cc3d9a517656e07a4c'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187401010300-187501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187401010300-187501010000.nc' 'SHA256' '806999af3b3a9d8c64f05e177f2ccb9f2abf674eddb6e32afb1d5f041015520d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187501010300-187601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187501010300-187601010000.nc' 'SHA256' 'd7e85d819fcef17f557ffdea98ecdbf7840698e5614e9d56173f10e14a4afb6b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187601010300-187701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187601010300-187701010000.nc' 'SHA256' '4af90ed88409b7c53dea5bffe676d21ce157d8ccaa31cd18a058cd0bdccaa298'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187701010300-187801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187701010300-187801010000.nc' 'SHA256' 'f368c281610f7b88f85aa708dbcad6e3a94310d3667f1c599f69c3e349dd21ce'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187801010300-187901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187801010300-187901010000.nc' 'SHA256' 'f975222b9499608b9fe68a8814616bffcde109cf368c1eea584bb8f2539685e6'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187901010300-188001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_187901010300-188001010000.nc' 'SHA256' '3d198d5e7daa5fc6837d8fa102ad160df5a071d78356ce6a0b219c86eeee9748'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188001010300-188101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188001010300-188101010000.nc' 'SHA256' 'afe9d42d9ef77d99a3c0eb770f807f10778364d8b2ce2bccd30f692fc5a152da'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188101010300-188201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188101010300-188201010000.nc' 'SHA256' 'ce2c188b065887efdf57cae0512578af2bfb859599054b4dbc937d68b15448aa'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188201010300-188301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188201010300-188301010000.nc' 'SHA256' '879adf387a6abeafa267bd073a9830c356cf155f7dbd1b975c044994e0971322'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188301010300-188401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188301010300-188401010000.nc' 'SHA256' '87a36e3fc0db6eedf2d1be09044217682791ffdbeabf55fb8b945e8ba4dec9d5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188401010300-188501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188401010300-188501010000.nc' 'SHA256' '7e79a49bbe012022cadf668b153f68915d875aef2a9c06cafa77a77c681358d3'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188501010300-188601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188501010300-188601010000.nc' 'SHA256' 'fc6ae525566d6daf9e559fa872c2e752beadfb38415874395b1c4f07eea0cff0'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188601010300-188701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188601010300-188701010000.nc' 'SHA256' 'd4e23ff2d927362795f85cf6cbe78dd584c7f5f904368d046ef0b892dc84c3be'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188701010300-188801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188701010300-188801010000.nc' 'SHA256' '8c268e944014349814597e9db9c8da8ac6ae697cdf05aa3b932c295acefae56a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188801010300-188901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188801010300-188901010000.nc' 'SHA256' 'baa9570bfb88936afd749dbd5df21041a497e40e8f3bfe8c0435cf1d064a855a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188901010300-189001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_188901010300-189001010000.nc' 'SHA256' 'b1b80f4c3f75108ab47cd1d4207f159026d0ba6a7ee64e7c0aeef79f13f01370'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189001010300-189101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189001010300-189101010000.nc' 'SHA256' '65d34f3652c4d2ac378325ed338d477a016f9a969256a312d84a46b07f5a9c3f'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189101010300-189201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189101010300-189201010000.nc' 'SHA256' '0ebe3a81f2ca565458f7231a38b5fee212ca88dcc77c49abdfb56410e6b2b93a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189201010300-189301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189201010300-189301010000.nc' 'SHA256' '0e80d2dd5d2d1491f96ac57f4e0696d0855d51b31f20105490fc40cf1b65825f'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189301010300-189401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189301010300-189401010000.nc' 'SHA256' '22be5401e1d773e1daf98f823e3b2826fe51eac1ca334872e28d666c6c1b53c4'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189401010300-189501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189401010300-189501010000.nc' 'SHA256' 'a4c8b6351d708e84ac813ea69cbd23e47b316619002734c47fdd136f25c85aae'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189501010300-189601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189501010300-189601010000.nc' 'SHA256' '87da1d263d351661ca0262b6e76643767ace79a5f03a111809bddbdb28c165d7'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189601010300-189701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189601010300-189701010000.nc' 'SHA256' '7722bc75b0a7f2556ef8aca31cbc2c8da87da9886881ee209e12e5fdb0716f6e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189701010300-189801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189701010300-189801010000.nc' 'SHA256' '1c2a704b32298c2125a49f2111f9c820c3cd56b349c083510a14367dd5d2e775'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189801010300-189901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189801010300-189901010000.nc' 'SHA256' 'ff5d4df1c04ab09fe891228aa11105d50a0f70ab1ca2b757b22dc4c33a0afe66'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189901010300-190001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_189901010300-190001010000.nc' 'SHA256' '393f0c4ce872ed2c8b2aafdab1d3b28655aef4c073ef6a20cfd5966198c8c3aa'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190001010300-190101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190001010300-190101010000.nc' 'SHA256' 'ef6f61bae96b5661131d7468276e642e7e15106a9391205f97cc280e00c44757'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190101010300-190201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190101010300-190201010000.nc' 'SHA256' '2d2d45e57e795ec27740b21a3a218ac24bf4f3666524c607b49405905e2e657b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190201010300-190301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190201010300-190301010000.nc' 'SHA256' 'f1e8bb526ffe1471f497e70fb03fb381288c177b0a35a826ac535583109e5132'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190301010300-190401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190301010300-190401010000.nc' 'SHA256' 'ce14cdd6c2c4dcbc3e79a16594ae89010f87d9e6b57f5e64b2c169993b68631b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190401010300-190501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190401010300-190501010000.nc' 'SHA256' '9cc9f394038e3f300d886973264ccbb4332ba54205d6f6cad345afa3e418114c'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190501010300-190601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190501010300-190601010000.nc' 'SHA256' '48eda56cf68027fb47f03bed39c78427ba0cac0297bac2f1af018197154f16d8'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190601010300-190701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190601010300-190701010000.nc' 'SHA256' '22fbc3cd82a25d29e4ca2c7e3020c19273d07eb363bade8c01f0310aa3d526ea'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190701010300-190801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190701010300-190801010000.nc' 'SHA256' '74de19beb250e5016c38e00eb111c6c6598103187ce78f3732ca5d3432c5726e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190801010300-190901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190801010300-190901010000.nc' 'SHA256' 'c53e93710d5e4a486c9dea8c7b6bf118f3528463291c910341136601cfc49448'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190901010300-191001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_190901010300-191001010000.nc' 'SHA256' '71a655dbcb911003e51ccd56191c522b3cdf268490431c144c2593923cb5aa25'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191001010300-191101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191001010300-191101010000.nc' 'SHA256' '131f3815f9297310ca683220f3eff76dcb6e6479612aff822d9168fafb2d40b6'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191101010300-191201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191101010300-191201010000.nc' 'SHA256' '2e5ad61c42fccb602e8ecdc834e9ee5580051ca1b4f74d0104d3f9dabe7a6a2c'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191201010300-191301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191201010300-191301010000.nc' 'SHA256' '2d9ba8f9f8398585d1a37f4529c355bbf714ca32911583d8c58f5bfb2c7d0aed'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191301010300-191401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191301010300-191401010000.nc' 'SHA256' '37f4f49d3a475daef50526f3eef215483935baae1c24719362bf0994f50369b9'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191401010300-191501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191401010300-191501010000.nc' 'SHA256' 'ac3df8b504597dec5f997a790580fa425d78371d724bdeca6c11f23d64bfc8da'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191501010300-191601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191501010300-191601010000.nc' 'SHA256' 'b81321a6140dd02950e1e340247f0c33abfaae15bef11921d499a252e25097b8'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191601010300-191701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191601010300-191701010000.nc' 'SHA256' '172b2322576e2d1a59a01b11096b47ee1ff1d61c23c9ef0b65261200188dbb2d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191701010300-191801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191701010300-191801010000.nc' 'SHA256' '445be08fe2f2ef54f4c01ab7c73fda66ac8d9c93f0e5714dc374dd55d3de7a0c'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191801010300-191901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191801010300-191901010000.nc' 'SHA256' 'bcf5f045f9b3fea34327a6a975c2fb78c3e40bb0a61b99edd47e34d881b272de'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191901010300-192001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_191901010300-192001010000.nc' 'SHA256' 'ac23eccbb4ac39ddfb3517b2f8572995e1eb35d9b584ffb0ed808329f7801926'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192001010300-192101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192001010300-192101010000.nc' 'SHA256' 'f62d7a92e6564662b5b0921dd7a915570452ac92bd5b069cf3190bf30f3c374d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192101010300-192201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192101010300-192201010000.nc' 'SHA256' '8e82624314d61c411bdd003ba09a133e0b5e2dcc364e1c20e390c058b21ceebc'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192201010300-192301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192201010300-192301010000.nc' 'SHA256' '7c39f3b9f1427c86a768dcb72e81347f109ac7c6ee9cafc114c6c6c0fad32565'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192301010300-192401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192301010300-192401010000.nc' 'SHA256' '5f520e78b4190695d88d9b6fecaab071b6d109fb731838f452b28ecba4d36d38'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192401010300-192501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192401010300-192501010000.nc' 'SHA256' 'b75ac6a757c32892a3a5f950adf8ea65d68778398ad7d0c3b24142c6c008229f'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192501010300-192601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192501010300-192601010000.nc' 'SHA256' 'e88d1455f7e0fd64297c40ee41915e6fe14836ba4df18e3084847a97623488d6'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192601010300-192701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192601010300-192701010000.nc' 'SHA256' '6f7614e317e5df5b8fb94176db7ec0c0185764b1403a4edf431ccfa65a78ee0e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192701010300-192801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192701010300-192801010000.nc' 'SHA256' '7d32efd2a596bd9a6e5c5ec1af3c670fde8ccbe0e959a7b83be3435f3edd1d07'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192801010300-192901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192801010300-192901010000.nc' 'SHA256' '85aa235257c6514e3c4ccdc894036fb5aad6ba0704af13b0cf44849a02dba1f9'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192901010300-193001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_192901010300-193001010000.nc' 'SHA256' 'a4e942efe82f1a88449dbca2fc4fbabc8ccac8815f36cd8def25a269ff273421'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193001010300-193101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193001010300-193101010000.nc' 'SHA256' 'ed4256ca4f8e2652c00b1c1a41d74de49d638edbfc472fb28a07bb9cab1e9b29'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193101010300-193201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193101010300-193201010000.nc' 'SHA256' 'a43690f4a3c67c10bfab4a84396c190b4a653449230b8761616fec6575b8baba'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193201010300-193301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193201010300-193301010000.nc' 'SHA256' 'd70d000cf94b6fd5fa90bb3e10e1549c65542001e912d443cb6b5eee950ab9f5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193301010300-193401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193301010300-193401010000.nc' 'SHA256' 'b7772e8bfe8a5b1d521f8f4b6c629c63da702cd9241d7f9f0d35b7c3e3c02678'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193401010300-193501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193401010300-193501010000.nc' 'SHA256' 'c81bada8b78a8db723dd6637bfbeff70ab541f5ca1ebc512fde2a236b1e6f4cd'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193501010300-193601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193501010300-193601010000.nc' 'SHA256' '9431471872dcb60a68cf924341b3fef3b00ae73b926c907ec065acaf8a0c9d30'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193601010300-193701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193601010300-193701010000.nc' 'SHA256' 'db739ddf2b6af92c95958b92ba67e1aa8a7b84c5cf12537d00372e7a36e244a6'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193701010300-193801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193701010300-193801010000.nc' 'SHA256' 'caf6d029e989822ef4c1dc03ee249240e55cb6e0262b3417af0150090a474243'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193801010300-193901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193801010300-193901010000.nc' 'SHA256' '85d66aa20119f197cc914d51d0394a377f132e8b968f61fb7edbf9aa6f236af0'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193901010300-194001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_193901010300-194001010000.nc' 'SHA256' 'b37ce8b7064f737f9ebd1715d27d66f88b38e7e453130c1b507748123ab7b7f3'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194001010300-194101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194001010300-194101010000.nc' 'SHA256' '375573b12fd49631ae482ce49fcfd07bba7dd4fb7e8cdf376f657d08b9ed76f8'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194101010300-194201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194101010300-194201010000.nc' 'SHA256' '2e95ca572ee15f5f801abe7dd84c88f3f56985d17d85a53a0960ff80a3f9d372'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194201010300-194301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194201010300-194301010000.nc' 'SHA256' 'cc36a78fab703d30375493fa8659efea7cc0ddc7b07dd01ff1f16f2e6ffbfe48'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194301010300-194401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194301010300-194401010000.nc' 'SHA256' '9cd0cd7b899d59844c61d46dae17a5d22fb1c2bccb7508e5c6a9e65004716352'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194401010300-194501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194401010300-194501010000.nc' 'SHA256' '3746d479e953b60861af7d0bc162c8a0082d4484916f2bee5445985665788f6b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194501010300-194601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194501010300-194601010000.nc' 'SHA256' '165958fe4a24d821f71da7c7d1c098d26a9ec04e23d22df51b5f175809f00ef2'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194601010300-194701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194601010300-194701010000.nc' 'SHA256' '88f07e76a2e851e7e6862537eb3b50cbbb5cee347da25886538439e63a46e6c7'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194701010300-194801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194701010300-194801010000.nc' 'SHA256' '0db230a786702b7dc8daf9a9a08ceb0e7bcfe8d16311d18898caa370a9d96a2b'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194801010300-194901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194801010300-194901010000.nc' 'SHA256' 'c87270627b8440bc41c5772652981f0a36d85948cb722b523dfcb5b0d5f9c1e3'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194901010300-195001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_194901010300-195001010000.nc' 'SHA256' '2ab417b93e6c2fd1640369cc0d6e4117852b2f508a583e99642b9c0908c1f1ea'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195001010300-195101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195001010300-195101010000.nc' 'SHA256' 'f3f194382801d67db8475d9c39ca61b16fe70ddd3c72bcb0c707849a3e5f6d93'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195101010300-195201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195101010300-195201010000.nc' 'SHA256' '1c77a38e5eb4820764b97c11a1c45a4c6b54495625bd588f5b20379621853c92'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195201010300-195301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195201010300-195301010000.nc' 'SHA256' 'cdaeb230091e1a755ccf3272a445c45d91adbe106ce1cb0e5af08a94d716608d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195301010300-195401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195301010300-195401010000.nc' 'SHA256' '9dee96f2a7f57e87f1dbbad656001d65486bad081c17fb40d5a55cd80c2ea632'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195401010300-195501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195401010300-195501010000.nc' 'SHA256' 'e7e6f79a9a7112652cef41af21021466933452335252d53f5504f00a69443b3d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195501010300-195601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195501010300-195601010000.nc' 'SHA256' '9a7d956b0df72fd164c4ab0bb651fd45a52ba9a8c0a0e399444a79d123b29fd7'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195601010300-195701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195601010300-195701010000.nc' 'SHA256' '18f62072b2f0d169730bc4160d317f150975e78267d7669f4bb775653ede1bec'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195701010300-195801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195701010300-195801010000.nc' 'SHA256' 'a16d9d1344eaae7d6812812e00390056e2f07bf635232c5c7e2d93c6fd04a51a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195801010300-195901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195801010300-195901010000.nc' 'SHA256' 'cafcb9273cd8da88e86a1e8716564791b2bb7b326dd43b27face7fbe7c438270'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195901010300-196001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_195901010300-196001010000.nc' 'SHA256' 'bd85224f6f5707263c671f2813c0ee1620321700b99cfffee6035b37bf6c9a19'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196001010300-196101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196001010300-196101010000.nc' 'SHA256' '7174378d29e5fd6072229d7a6e3b7df8462b8ff548625c7b9ca8d99c56d65ea4'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196101010300-196201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196101010300-196201010000.nc' 'SHA256' '4fa71cc7ce79e756da4be716338679183639142a89a8fb3e68a806da0d004ba3'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196201010300-196301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196201010300-196301010000.nc' 'SHA256' 'd4cd946f0fa4d732a1e7449d3d90ed228842721039e42954a485c054fbded64e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196301010300-196401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196301010300-196401010000.nc' 'SHA256' 'a6055ef247e8cc374711b628553bf58232890bd6750e22c4c30255d0d6eb95ba'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196401010300-196501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196401010300-196501010000.nc' 'SHA256' '36d412810b59dbf0c5feaff9bf989632d1d7db7d4baf69243be2b608313d2ad5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196501010300-196601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196501010300-196601010000.nc' 'SHA256' '6d80418b608001276603a7a772a77e750057f2a3adc180c0630925ffa0c3a24a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196601010300-196701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196601010300-196701010000.nc' 'SHA256' '7e931d315c2a0ba9756a688cf29978a862cb81c5457fc805804f96ffaee9c85e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196701010300-196801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196701010300-196801010000.nc' 'SHA256' 'd6d2393290e3d77a8d97f41e8ccfc56d5338f0f24bb17e1f9398e45c084ff70a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196801010300-196901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196801010300-196901010000.nc' 'SHA256' '347f0782f63c58d9fb2f4907f7a59057a3c5059cf761be31dcfde29b5598a49e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196901010300-197001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_196901010300-197001010000.nc' 'SHA256' 'c857168e95202d8f4bf3bb982a1d70d1fb8a93bd4f1af69a27614163b0b43ab2'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197001010300-197101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197001010300-197101010000.nc' 'SHA256' 'e780ff465c49b8ba7287f81caad8d32a1db7d798829cbd4915ef6489e40372c7'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197101010300-197201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197101010300-197201010000.nc' 'SHA256' '63e68d198d0ca30806ff9711472e1e0dfb84145138422d8d1f17261a3fde3f32'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197201010300-197301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197201010300-197301010000.nc' 'SHA256' '57bf39d1f1013562e38be29ab05328bcbb0421198f6da033e2faab0d0a0a687d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197301010300-197401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197301010300-197401010000.nc' 'SHA256' 'e55dd5e6b2dabeab51a57b8c7747e028e4ada6e68e051bc6b610e1d6d4815427'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197401010300-197501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197401010300-197501010000.nc' 'SHA256' 'df4b88c065437876f5c0476cbc45f290c04c0cc7a7bb928f16ba9b44c050da06'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197501010300-197601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197501010300-197601010000.nc' 'SHA256' '5ef3f7985a1c27544cd7e902c3bf14195890e34cddde8b27fa9b82cc4a74b950'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197601010300-197701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197601010300-197701010000.nc' 'SHA256' '3403b81bf41137c58809e3a026fbf63070e54a57c09dbeb932926bc17320ab3f'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197701010300-197801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197701010300-197801010000.nc' 'SHA256' '53ae90d8c44286a99f1fa236f4ee7b6f67a82cdf2c661ce7fe21ac1255677b81'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197801010300-197901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197801010300-197901010000.nc' 'SHA256' '241047939c23c9cf37c3c7ae8daecfc235215406a6ad5ffdbdcc267ba17a8c4e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197901010300-198001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_197901010300-198001010000.nc' 'SHA256' 'd94ee48d886567cea1fff68e8dacf3bad979f87a98144f694eb3c62cbf5ca426'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198001010300-198101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198001010300-198101010000.nc' 'SHA256' '9dde16fe5ecc768d74334bd15eb282c5ad4e1ec5ca221ff5ea3730bc345e19ab'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198101010300-198201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198101010300-198201010000.nc' 'SHA256' '8b337da3c790f2941979b8e36bc4c7a29f4196889c7a825ca47d6e14d837c745'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198201010300-198301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198201010300-198301010000.nc' 'SHA256' 'c9ea15c1bb7de83d23fec223c7e72feed9b6858a4c35433fbf64506826490347'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198301010300-198401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198301010300-198401010000.nc' 'SHA256' '399b2817755b989de074cee0b6789fe127d861dd9c6c0e7ce98a5e37992330b4'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198401010300-198501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198401010300-198501010000.nc' 'SHA256' 'f06397ed23d2a15841251b8b645460f3f8f663b457298d79b700be629849dcbc'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198501010300-198601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198501010300-198601010000.nc' 'SHA256' '06486764adb906c3ac5f7cd3da2094a9c29630a56a56583ca896eaea1831cafb'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198601010300-198701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198601010300-198701010000.nc' 'SHA256' '4cc27ec89ec735eab3d83937528a08195214543b5ef8f47684f48890b80015bc'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198701010300-198801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198701010300-198801010000.nc' 'SHA256' 'c8ef54dab4c0a4f3ea6b39efc7e069994fa6f1e08b813434afc6c349bf055f57'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198801010300-198901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198801010300-198901010000.nc' 'SHA256' 'd2b2e732eea6b5e1a84845653b52f7e81288da64fc114776ae09f4234efcdb59'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198901010300-199001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_198901010300-199001010000.nc' 'SHA256' 'd3c4fd059cf5909a07326c5ebf65a84bef8cfd899d04c265b37f07363586e795'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199001010300-199101010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199001010300-199101010000.nc' 'SHA256' 'f350c9ab01d45137c85be02725eaf87067be94d34c50aac8e0f512e65308d19e'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199101010300-199201010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199101010300-199201010000.nc' 'SHA256' '14fd88e6b06ae8f7010c45e5e57b78b2acca6fbc5663cd6ee39810625b2db405'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199201010300-199301010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199201010300-199301010000.nc' 'SHA256' '1a4d55bb7459a82a05b86f4fce3b40b7b4ef58c70b73df37c7a8e6088e92869a'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199301010300-199401010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199301010300-199401010000.nc' 'SHA256' '4d9365b46d79cc94396c584e7024e8328ddc81eee89b4f8b9bfc368b83cd9273'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199401010300-199501010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199401010300-199501010000.nc' 'SHA256' 'c1b9c2fad2cf236a8f55ed8287f25210f2ac4bb7a29e34a3b87014c59930b16c'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199501010300-199601010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199501010300-199601010000.nc' 'SHA256' 'bf5930851323a4bd7e2f8b9f12538981305fa1f96c975de41877e2aa3650bef5'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199601010300-199701010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199601010300-199701010000.nc' 'SHA256' '8ecfa5f06ef9ac3f1b5cd85475570624dccb7861d420d0565d88d9e2ff3fc34d'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199701010300-199801010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199701010300-199801010000.nc' 'SHA256' '5a8a37baf6f0098e4648d0a6a7a8d08691c584ee25fb91f888e155ddcca01416'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199801010300-199901010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199801010300-199901010000.nc' 'SHA256' '5b834944a47042131f2883f82dca10da1d9beb61401e52b0b2bfb35d64de4ead'
'huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199901010300-200001010000.nc' 'http://esgf-data02.diasjp.net/thredds/fileServer/esg_dataroot/CMIP6/LUMIP/MIROC/MIROC-ES2L/deforest-globe/r1i1p1f2/3hr/huss/gn/v20220506/huss_3hr_MIROC-ES2L_deforest-globe_r1i1p1f2_gn_199901010300-200001010000.nc' 'SHA256' 'c15f435cbf581419e5ad3d01a45d76dcf864a86eb2bb4d080b317a9b0e0872d5'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 150 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
